version: '3.7'
services:
  nginx:
    image: nginx:1.18
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./app:/app
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - '8080:80'
  php-fpm:
    build:
      context: ./docker/dev
      dockerfile: php-fpm/Dockerfile
      args:
        WWWGROUP: 1000
        WWWUSER: 1000
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      TZ: "Europe/Moscow"
      PHP_IDE_CONFIG: serverName=mappa
  db:
    image: postgres:13
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
